### ISSUE TITLE
6.10.3 kernel causing invalid opcode traps unless GDS mitigation is disabled

### ISSUE THREAD

**Issue by tormodvolden** [linux-surface/kernel#156]
Please see all bug reports from last week at https://github.com/linux-surface/linux-surface/issues
I double-posted in https://github.com/linux-surface/linux-surface/issues/1534

In my case it is always in libgnutls.so but also libxul.so was reported in https://github.com/linux-surface/linux-surface/issues/1529

Some examples:
```
https[4515] trap invalid opcode ip:7bd64c2a03ca sp:7ffeb94d9c80 error:0 in libgnutls.so.30.31.0[1583ca,7bd64c179000+129000]
pool-fwupdmgr[5068] trap invalid opcode ip:7e75c309663e sp:7e75be1fedc0 error:0 in libgnutls.so.30.31.0[15363e,7e75c2f74000+129000]
wireplumber[1026] trap invalid opcode ip:733ef036863e sp:733ee9ffe9c0 error:0 in libgnutls.so.30.31.0[15363e,733ef0246000+129000]

```

**Comment by tormodvolden** [comment]
It looks like an upstream issue because the same happens (but maybe to a lesser degree) with a stock 6.10.3 kernel (6.10.3-061003-generic from https://kernel.ubuntu.com/mainline/v6.10.3/).
```
[   18.326145] traps: pool-geoclue[1842] trap invalid opcode ip:78816136d3ca sp:7881529fec80 error:0 in libgnutls.so.30.31.0[1583ca,788161246000+129000]
[  130.003878] traps: https[2358] trap invalid opcode ip:7824afa173ca sp:7ffd3e7fe480 error:0 in libgnutls.so.30.31.0[1583ca,7824af8f0000+129000]
[  130.062112] traps: https[2357] trap invalid opcode ip:7ebba6c7f3ca sp:7ffc290a6c80 error:0 in libgnutls.so.30.31.0[1583ca,7ebba6b58000+129000]
[  148.615892] traps: https[2487] trap invalid opcode ip:7fa21652e3ca sp:7fff4cf11480 error:0 in libgnutls.so.30.31.0[1583ca,7fa216407000+129000]

```

**Comment by tormodvolden** [comment]
This is caused by GDS attack mitigation disabling the AVX instruction because no patched microcode is available for these old processors:
```
$ sudo dmesg | grep -i microcode
[    0.121823] SRBDS: Mitigation: Microcode
[    0.121833] GDS: Microcode update needed! Disabling AVX as mitigation.
[    0.121835] GDS: Mitigation: AVX disabled, no microcode
[    0.981247] microcode: Current revision: 0x000000f0
[    0.981250] microcode: Updated early from: 0x000000ea
```
A workaround is to disable the "GDS" mitigation, by adding gather_data_sampling=off to the kernel command line.
```
$ sudo dmesg | grep -i microcode
[    0.121547] SRBDS: Mitigation: Microcode
[    0.121548] GDS: Vulnerable: No microcode
[    0.973064] microcode: Current revision: 0x000000f0
[    0.973066] microcode: Updated early from: 0x000000ea
```
The AVX instruction will no longer be disabled, and the invalid opcode traps are gone.

Note this leaves your computer vulnerable to GDS attacks, see e.g. https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/GDS_Downfall

**Comment by qzed** [comment]
GDS mitigation has been in the kernel for quite a while, but it looks like Ubuntu changed to `CONFIG_MITIGATION_GDS_FORCE=y` with v6.10. Could you compile a kernel with that disabled (meaning `CONFIG_MITIGATION_GDS_FORCE=n`) and check if that helps?

**Comment by tormodvolden** [comment]
Ah, thanks for pinpointing this. I had searched long for any relevant changes in the upstream changelog, but didn't go through the Ubuntu configuration.

When GDS force mitigation appeared in the kernel, with default "y", it created a lot of issues like these and Ubuntu quickly patched all their kernels, this from the 6.2.0-28.29_6.2.0-31.31 diff:

```
diff -u linux-6.2.0/debian.master/changelog linux-6.2.0/debian.master/changelog
--- linux-6.2.0/debian.master/changelog
+++ linux-6.2.0/debian.master/changelog
@@ -1,3 +1,13 @@
+linux (6.2.0-31.31) lunar; urgency=medium
+
+  * lunar/linux: 6.2.0-31.31 -proposed tracker (LP: #2031146)
+
+  * libgnutls report "trap invalid opcode" when trying to install packages over
+    https (LP: #2031093)
+    - [Config]: disable CONFIG_GDS_FORCE_MITIGATION
+
+ -- Thadeu Lima de Souza Cascardo <cascardo@canonical.com>  Mon, 14 Aug 2023 08:29:52 -0300
+
 linux (6.2.0-28.29) lunar; urgency=medium
 
   * lunar/linux: 6.2.0-28.29 -proposed tracker (LP: #2030547)
diff -u linux-6.2.0/debian.master/config/annotations linux-6.2.0/debian.master/config/annotations
--- linux-6.2.0/debian.master/config/annotations
+++ linux-6.2.0/debian.master/config/annotations
@@ -4992,7 +4992,7 @@
 CONFIG_GCC_VERSION                              policy<{'amd64': '120200', 'arm64': '120200', 'armhf': '120200', 'ppc64el': '120200', 'riscv64': '120200', 's390x': '120200'}>
 CONFIG_GCOV_KERNEL                              policy<{'amd64': 'n', 'arm64': 'n', 'armhf': 'n', 'ppc64el': 'n', 'riscv64': 'n', 's390x': 'n'}>
 CONFIG_GDB_SCRIPTS                              policy<{'amd64': 'y', 'arm64': 'y', 'armhf': 'y', 'ppc64el': 'y', 'riscv64': 'y', 's390x': 'y'}>
-CONFIG_GDS_FORCE_MITIGATION                     policy<{'amd64': 'y'}>
+CONFIG_GDS_FORCE_MITIGATION                     policy<{'amd64': 'n'}>
 CONFIG_GEMINI_ETHERNET                          policy<{'arm64': 'm', 'armhf': 'm', 'ppc64el': 'm', 'riscv64': 'm'}>
 CONFIG_GENERIC_ADC_BATTERY                      policy<{'amd64': 'm', 'arm64': 'm', 'armhf': 'm', 'ppc64el': 'm', 'riscv64': 'm'}>
 CONFIG_GENERIC_ADC_THERMAL                      policy<{'amd64': 'm', 'arm64': 'm', 'armhf': 'm', 'ppc64el': 'm', 'riscv64': 'm'}>
```

In 6.10 the option was renamed from CONFIG_GDS_FORCE_MITIGATION but when Ubuntu jumped from 6.8 to 6.10, this customization was lost, from the 6.8.0-31.31_6.10.0-15.15 diff:
 ```
 CONFIG_GDB_SCRIPTS                              policy<{'amd64': 'y', 'arm64': 'y', 'armhf': 'y', 'ppc64el': 'y', 'riscv64': 'y', 's390x': 'y'}>
-CONFIG_GDS_FORCE_MITIGATION                     policy<{'amd64': 'n'}>
 CONFIG_GEMINI_ETHERNET                          policy<{'arm64': 'm', 'armhf': 'm', 'ppc64el': 'm', 'riscv64': 'm'}>
...
 CONFIG_MITIGATE_SPECTRE_BRANCH_HISTORY          policy<{'arm64': 'y'}>
+CONFIG_MITIGATION_CALL_DEPTH_TRACKING           policy<{'amd64': 'y'}>
+CONFIG_MITIGATION_GDS_FORCE                     policy<{'amd64': 'y'}>
+CONFIG_MITIGATION_IBPB_ENTRY                    policy<{'amd64': 'y'}>
+CONFIG_MITIGATION_IBRS_ENTRY                    policy<{'amd64': 'y'}>
```
I am sure this was an oversight, and that the old option was simply dropped because it didn't exist any longer, without thinking of it being renamed (among a lot of other renames).

(I have filed an Ubuntu bug for this at https://bugs.launchpad.net/bugs/2077145)

Based on the above, I believe the whole situation is understood, and I won't compile a kernel for testing.

**Comment by qzed** [comment]
I checked the config of the 6.9.9 kernel and it had the option disabled. So I assume that the upstream 6.9 config we pulled for that also has this disabled.

I'll disable it in our config overrides.

**Comment by qzed** [comment]
And thanks for figuring out that GDS is the issue.

**Comment by qzed** [comment]
Should be fixed in https://github.com/linux-surface/linux-surface/commit/4439a5efb6516c443df5f52173cb55aef01560d1. I'll try to update the patches and push a new release either this evening or tomorrow.

**Comment by qzed** [comment]
Latest releases should be out and things should work with those again. If things don't work, let's continue this in https://github.com/linux-surface/linux-surface/issues/1534.
