### ISSUE TITLE
I cannot boot 6.10.x kernels

### ISSUE THREAD

**Issue by Valerio1474** [linux-surface/kernel#157]
I've updated my Debian installation on a Surface Pro 9 and I discovered that both 6.10.3 and 6.10.5 kernels can't boot. My only working kernel was the 6.9.3 version then I tried to install 6.9.9 and it works too.
Below there are the pictures of the errors I got on boot when trying to start a 6.10.x kernel.

**Comment by Valerio1474** [comment]
![20240817_184722](https://github.com/user-attachments/assets/451f0bc5-0360-4d5e-95c1-0b3072937224)

**Comment by Valerio1474** [comment]
![20240817_184708](https://github.com/user-attachments/assets/2dc92cbc-4f1c-4fb3-ab70-dc2994939ed7)

**Comment by Valerio1474** [comment]
![20240817_184708](https://github.com/user-attachments/assets/abe2f4c1-6f98-4f70-bcaa-a196365aa00a)

**Comment by qzed** [comment]
Workaround for now: [blacklist the ipu6 modules](https://github.com/linux-surface/linux-surface/issues/1516#issuecomment-2269662870).

**Comment by Valerio1474** [comment]
Yes! It's working now. Good workaround.

**Comment by qzed** [comment]
I'll close this here then, let's continue this in https://github.com/linux-surface/linux-surface/issues/1516.
