### ISSUE TITLE
MS Surface Pro 7 - Error Communicating to TMP Chip

### ISSUE THREAD

**Issue by Vinc098** [linux-surface/kernel#25]
![IMG_20191228_053021](https://user-images.githubusercontent.com/59301959/71539029-0b226e00-2936-11ea-81d6-2120da80259d.jpg)

Hi, I need your help. I'm tried everything to run Linux (Ubuntu 19.10, other OS' doesn't work either) on my surface pro 7. The live-usb-Stick works (tried it on my desktop PC).
In UEFI the Secure-Boot is off + TMP Chip is on. (Tried it with TMP off, than it doesn't boot, too. Does anyone knows a workaround? 
Please explain it more detailed, because I'm new with Grub/booting Linux.

PS: My Windows 10 (same SSD other partition) is encrypted with Bitlocker.

Thanks.

**Comment by qzed** [comment]
That's a known issue, see for example https://github.com/jakeday/linux-surface/issues/592#issue-511404366. Specifically:

> * Kernel parameter `modprobe.blacklist=intel_lpss_pci`, otherwise system hangs as `intel-lpss` loads.

Meaning, you have to edit the kernel parameters before booting into the live image (see e.g. https://help.ubuntu.com/community/BootOptions under "Changing the CD Boot Option Configuration Line") and add `modprobe.blacklist=intel_lpss_pci` at the end.

**Comment by Vinc098** [comment]
Thank you so much. It worked. 

Do you know any kernel (Debian) that supports touch input/pen input for the surface pro 7?

tried out some mentioned here on github without luck.

**Comment by qzed** [comment]
See #22 for the status on that. I'm not aware of any other project trying to support IPTS devices on the newer kernels.

**Comment by qzed** [comment]
Closing as main issue is resolved.
