### ISSUE TITLE
Surface Pro 7 Kernel that support touch

### ISSUE THREAD

**Issue by Vinc098** [linux-surface/kernel#27]
Is there any Ubuntu/Debian Kernel that support touch or stylus input on my Surface Pro 7. I installed this on https://github.com/linux-surface/linux-surface but it doesn't enable touch. Have I something forgotten to do? (Yes, I booted the surface-kernel)

**Comment by StollD** [comment]
Closing as a duplicated, please refer to #22 for touchscreen support on gen7.
