### ISSUE TITLE
Backporting 5.3/5.4 changes into 4.19

### ISSUE THREAD

**Issue by kitakar5525** [linux-surface/kernel#31]
dumping all the commit log made by linux-surface and reporting backporting status here.

commit in 4.19:
☑: means both 5.3 and 4.19 have corresponding commit (according to commit title)
✅(only in 4.19)
⚪(in 4.19 and 5.4)

commit irrelevant to 4.19:
✅(merge commit)
✅(legacy-i915)
✅(outdated-patch)

commit not in 4.19 but corresponding change already done:
✅(already available in 4.19)

commit not in 4.19 (no meaning in emojis, just for visibility):
- ~[ ] ❓(not sure if needed for 4.19)~
- [x] ❌(old-patches-cleanup)
- [x] 🚳(bugfix/touch-rotation) https://github.com/linux-surface/kernel/pull/3
- [x] 🔺(feature/no-ipts-config-file) https://github.com/linux-surface/kernel/pull/11
- [x] 🙅(feature/ipts-cleanup) https://github.com/linux-surface/kernel/pull/15
- [x] 🚫(feature/companion-no-feedback) https://github.com/linux-surface/kernel/pull/16
- [x] 🉐(wifi-suspend-fix)
- [x] 🈲(feature/ipts-no-modeswitch) https://github.com/linux-surface/kernel/pull/23

The checkbox shows backport status on https://github.com/kitakar5525/linux-surface-kernel/tree/backport/v4.19-surface-devel

<details><summary>4.19</summary>
<p>

☑ dce8429a0cad - kitakar5525, 2020-01-11 : Surface3-OEMB: surface3-wmi: add quirk for Surface 3 with broken DMI table
☑ 7384203fbfed - Chih-Wei Huang, 2018-09-18 : Surface3-OEMB: ASoC: add quirk for Surface 3 with broken DMI table
☑ 62ac18af7e25 - Maximilian Luz, 2019-12-30 : surface_acpi: Remove indirect dependencies
☑ ccb08bd45416 - kitakar5525, 2019-12-06 : surface3-spi: workaround: disable DMA mode to avoid crash by default
☑ 3e10103b13f8 - Maximilian Luz, 2019-12-27 : surface_acpi: Integrate dGPU hot-plug system
☑ c4b9193f2b40 - Maximilian Luz, 2019-12-27 : Revert "platform/x86: Add support for Surface Book 2 dGPU"
☑ 5717e139f62c - Maximilian Luz, 2019-12-05 : surface_acpi: Default-disable wakeup on SSH
☑ 160e224c3054 - Maximilian Luz, 2019-12-04 : surface_acpi: Add battery/AC support via SID
☑ 2595b99509cb - Maximilian Luz, 2019-11-12 : surface_acpi: Add support for SAM HID devices
☑ 135f88124179 - Maximilian Luz, 2019-11-10 : surface_acpi: Split SID into MFD device
☑ cef457f78988 - Blaž Hrastnik, 2019-11-06 : HID: Improve Windows Precision Touchpad detection.
☑ 739ca58ef76e - Blaž Hrastnik, 2019-11-07 : Revert "HID: quirks for Microsoft Surface devices"
☑ dbb20f8c9190 - Maximilian Luz, 2019-11-06 : surface_acpi: Fix debug device config option name
☑ 3491789c4281 - Tuowen Zhao, 2019-10-16 : docs: driver-model: add devm_ioremap_uc
☑ f56c4bb9f9ba - Tuowen Zhao, 2019-10-16 : mfd: intel-lpss: use devm_ioremap_uc for MMIO
☑ d4b353d54e45 - Tuowen Zhao, 2019-10-16 : lib: devres: add a helper function for ioremap_uc
☑ 841fce3ff988 - Tuowen Zhao, 2019-10-16 : sparc64: implement ioremap_uc
☑ f8d6fd319ebb - Maximilian Luz, 2019-10-20 : surface_acpi: Update surface-acpi module
☑ 3aac3d3d333d - Hans de Goede, 2019-10-05 : Input: soc_button_array - partial revert of support for newer surface devices
☑ 470808b0b2b8 - Dorian Stoll, 2019-10-03 : Add firmware declarations for ipts_surface
☑ cfc5d927d6e7 - Maximilian Luz, 2019-10-17 : INTEL_IPTS: Add dependency on DRM_I915
☑ 9c30ab7bf5b9 - Maximilian Luz, 2019-10-02 : surface_acpi: Update DMI check for Surface Pro 5
☑ 468e384e8b1d - Maximilian Luz, 2019-09-28 : platform/x86: Add support for Surface Book 2 dGPU
☑ 9a9ae3930235 - Maximilian Luz, 2019-09-28 : USB: serial: Register Surface Go LTE device
☑ b026a27800fc - Maximilian Luz, 2019-09-28 : wireless: Add mwlwifi driver
☑ 935f6d2096e6 - Maximilian Luz, 2019-09-28 : platform/x86: Surface 3 battery platform operation region support
☑ 7f5940521b18 - Maximilian Luz, 2019-09-28 : wireless/mwifiex: Add quirks for Surface devices
☑ 218ad8f54786 - Maximilian Luz, 2019-09-28 : USB: Modify lpm check for sdcard-reader
☑ 1564ae6d3556 - Maximilian Luz, 2019-09-28 : HID: quirks for Microsoft Surface devices
☑ 8240743c1a1c - Maximilian Luz, 2019-09-28 : Add support for Intel IPTS touch devices
☑(contains typo) 36f3225b2f83 - Maximilian Luz, 2019-09-28 : staging: Add WIP camera drivers for Surfae devices
☑ d13cc153443a - Maximilian Luz, 2019-07-27 : Input: soc_button_array - Add support for newer surface devices
☑ aa86cce4c2b2 - Maximilian Luz, 2019-07-27 : platform/x86: surfacepro3_button: Fix device check
☑ 4bb6b4bae4f2 - Maximilian Luz, 2019-09-28 : power/suspend: Add delay for device quirks
✅(only in 4.19) 853c18517e83 - kitakar5525, 2019-09-28 : nvme: Backport changes for suspend
☑ 1b062be61be6 - Maximilian Luz, 2019-09-25 : platform: Add gen5 MS Surface platform support
⚪(in 4.19 and 5.4) 6a3fb10d0997 - Maximilian Luz, 2019-09-24 : serdev: Add ACPI devices by ResourceSource field
☑ 8d74ef941558 - qzed, 2019-08-26 : ACPI: Fix buffer/integer type mismatch
☑ 38f039c2a77f - Dorian Stoll, 2019-09-22 : Add secureboot pre-signing to the kernel
d573e8a79f70 - Greg Kroah-Hartman, 2019-09-21 : Linux 4.19.75

</p>
</details>

<details><summary>5.3</summary>
<p>

✅(merge commit) 9933f3c416f3 - Maximilian Luz, 2020-01-13 : Merge pull request #29 from kitakar5525/Surface3-OEMB
☑ 9c1f1f4dce2b - kitakar5525, 2020-01-11 : Surface3-OEMB: surface3-wmi: add quirk for Surface 3 with broken DMI table
☑ 85982debfc10 - Chih-Wei Huang, 2018-09-18 : Surface3-OEMB: ASoC: add quirk for Surface 3 with broken DMI table
☑ 749a4a619757 - Maximilian Luz, 2019-12-30 : surface_acpi: Remove indirect dependencies
✅(merge commit) 7f5a95a06477 - Maximilian Luz, 2019-12-27 : Merge pull request #24 from kitakar5525/surface3-touch-fix
☑ 7212ca8bf0bf - Maximilian Luz, 2019-12-27 :  surface_acpi: Integrate dGPU hot-plug system
☑ 341a07689523 - Maximilian Luz, 2019-12-27 : Revert "platform/x86: Add support for Surface Book 2 dGPU"
☑ 6c196dee2d1f - kitakar5525, 2019-12-06 : surface3-spi: workaround: disable DMA mode to avoid crash by default
✅(merge commit) a93d778a611e - Maximilian Luz, 2019-12-22 : Merge pull request #23 from StollD/feature/ipts-no-modeswitch
🈲(feature/ipts-no-modeswitch) 894fbba16b64 - Dorian Stoll, 2019-12-20 : ipts: Dont automatically switch sensor modes
🉐(wifi-suspend-fix) 8dbbfa681975 - sebanc, 2019-11-04 : wireless/mwifiex: Fix S0ix / suspend
🉐(wifi-suspend-fix) d95addefdf90 - Maximilian Luz, 2019-12-18 : Revert "wireless/mwifiex: Add quirks for Surface devices"
☑ 2d775a4073a1 - Maximilian Luz, 2019-12-05 : surface_acpi: Default-disable wakeup on SSH
☑ af731af03290 - Maximilian Luz, 2019-12-04 : surface_acpi: Add battery/AC support via SID
☑ 42110e9fdadc - Maximilian Luz, 2019-11-12 : surface_acpi: Add support for SAM HID devices
☑ b2dbb40eed79 - Maximilian Luz, 2019-11-10 : surface_acpi: Split SID into MFD device
✅(merge commit) 745dbed942ff - Maximilian Luz, 2019-11-10 : Merge pull request #16 from StollD/feature/companion-no-feedback
🚫(feature/companion-no-feedback) 55e49e161f2e - Dorian Stoll, 2019-11-10 : ipts: Add a generic interface for quirks
🚫(feature/companion-no-feedback) 40f343b1e2c2 - Dorian Stoll, 2019-11-08 : ipts: Let the companion decide about no_feedback
✅(merge commit) 600a4b7a8ee4 - Maximilian Luz, 2019-11-08 : Merge pull request #15 from StollD/feature/ipts-cleanup
🙅(feature/ipts-cleanup) 6fad9aa49409 - Dorian Stoll, 2019-11-07 : ipts: Document output of IPTS debug thread
🙅(feature/ipts-cleanup) 15585f5104cc - Dorian Stoll, 2019-10-28 : ipts: Remove ipts prefix from driver source files
🙅(feature/ipts-cleanup) ec34a3956834 - Dorian Stoll, 2019-10-28 : ipts: Move debugging settings into modparams
🙅(feature/ipts-cleanup) b7c60a63bd91 - Dorian Stoll, 2019-10-28 : ipts: Cleanup ipts-i915 to pass checkpatch
🙅(feature/ipts-cleanup) 16239438278a - Dorian Stoll, 2019-10-28 : ipts: Cleanup ipts-mei to pass checkpatch
🙅(feature/ipts-cleanup) 9f369e254dd7 - Dorian Stoll, 2019-10-28 : ipts: Update Makefile / Kconfig to pass checkpatch
🙅(feature/ipts-cleanup) 863de5488572 - Dorian Stoll, 2019-10-28 : ipts: Cleanup ipts-kernel to pass checkpatch
🙅(feature/ipts-cleanup) 1050bfc3d4f7 - Dorian Stoll, 2019-10-28 : ipts: Cleanup ipts-hid to pass checkpatch
✅(merge commit) f466f7d34efc - Maximilian Luz, 2019-11-07 : Merge pull request #14 from archseer/v5.3-surface-devel
☑ d45bc35c187c - Blaž Hrastnik, 2019-11-06 : HID: Improve Windows Precision Touchpad detection.
☑ 352b9fcff865 - Blaž Hrastnik, 2019-11-07 : Revert "HID: quirks for Microsoft Surface devices"
☑ 65dcd3b7afc7 - Maximilian Luz, 2019-11-06 : surface_acpi: Fix debug device config option name
🙅(feature/ipts-cleanup) 1fb6e1722904 - Dorian Stoll, 2019-10-28 : ipts: Cleanup public headers to pass checkpatch
🙅(feature/ipts-cleanup) c0556e16c3e2 - Dorian Stoll, 2019-10-28 : ipts: Cleanup ipts-surface to pass checkpatch
🙅(feature/ipts-cleanup) 0774af9cdab5 - Dorian Stoll, 2019-10-28 : ipts: Cleanup ipts-msg-handler to pass checkpatch
🙅(feature/ipts-cleanup) f63f75878486 - Dorian Stoll, 2019-10-28 : ipts: Cleanup ipts-companion to pass checkpatch
🙅(feature/ipts-cleanup) 24f97ef03eda - Dorian Stoll, 2019-10-27 : ipts: Cleanup ipts-gfx to pass checkpatch
🙅(feature/ipts-cleanup) 4aaed394991b - Dorian Stoll, 2019-10-27 : ipts: Cleanup ipts-state.h to pass checkpatch
🙅(feature/ipts-cleanup) 05f51be5b5d8 - Dorian Stoll, 2019-10-27 : ipts: Cleanup ipts-resource to pass checkpatch
🙅(feature/ipts-cleanup) 9c9dfad5cf62 - Dorian Stoll, 2019-10-27 : ipts: Cleanup ipts-params to pass checkpatch
🙅(feature/ipts-cleanup) 52e26dd098ed - Dorian Stoll, 2019-10-27 : ipts: Cleanup ipts-dbgfs.c to pass checkpatch
🙅(feature/ipts-cleanup) 30a9d306774c - Dorian Stoll, 2019-10-27 : ipts: Cleanup ipts-sensor-regs.h to pass checkpatch
🙅(feature/ipts-cleanup) bda10929972c - Dorian Stoll, 2019-10-27 : ipts: Clean up ipts.h to pass checkpatch
🙅(feature/ipts-cleanup) a16bb1619738 - Dorian Stoll, 2019-10-27 : ipts: Clean up ipts-mei-msg.h to pass checkpatch
✅(merge commit) 93d2b932b960 - Maximilian Luz, 2019-11-04 : Merge pull request #11 from StollD/feature/no-ipts-config-file
🔺(feature/no-ipts-config-file) 636e23d92ceb - Dorian Stoll, 2019-10-27 : ipts: Address comments by qzed and grayhatter
✅(merge commit) fe380f894e29 - Maximilian Luz, 2019-10-28 : Merge pull request #13 from qzed/v5.3-lpss-fix
☑ aceca893b4ad - Tuowen Zhao, 2019-10-16 : docs: driver-model: add devm_ioremap_uc
☑ 6f1806d2a519 - Tuowen Zhao, 2019-10-16 : mfd: intel-lpss: use devm_ioremap_uc for MMIO
☑ 127f1a729b43 - Tuowen Zhao, 2019-10-16 : lib: devres: add a helper function for ioremap_uc
☑ 9e250ff4f015 - Tuowen Zhao, 2019-10-16 : sparc64: implement ioremap_uc
🔺(feature/no-ipts-config-file) e1cfd8452ac9 - Dorian Stoll, 2019-10-20 : ipts: Move ipts_fw_config.bin into the companion
🔺(feature/no-ipts-config-file) a1531a7c0fb3 - Dorian Stoll, 2019-10-20 : ipts: Implement new companion interface
☑ b728e8997164 - Maximilian Luz, 2019-10-20 : surface_acpi: Update surface-acpi module
☑ d6e78a3f9f1f - Maximilian Luz, 2019-10-17 : INTEL_IPTS: Add dependency on DRM_I915
☑ 37287a3ecd01 - Hans de Goede, 2019-10-05 : Input: soc_button_array - partial revert of support for newer surface devices
✅(merge commit) e353b20ee3f2 - Maximilian Luz, 2019-10-03 : Merge pull request #7 from StollD/feature/initramfs-firmware
☑ 79f7d679f248 - Dorian Stoll, 2019-10-03 : Add firmware declarations for ipts_surface
☑ 2a9a217767d4 - Maximilian Luz, 2019-10-02 : surface_acpi: Update DMI check for Surface Pro 5
✅(already available in 4.19) d1adb85f5cec - Maximilian Luz, 2019-09-26 : scripts/sign_kernel: Change shell to bash
❓(not sure if needed for 4.19) e05aa9d2c9cd - Maximilian Luz, 2019-09-26 : platform/x86: Update surface-acpi
❓(not sure if needed for 4.19) 8667db5d1899 - Maximilian Luz, 2019-09-26 : serdev: Update ACPI lookup fix
✅(merge commit) d0ff7541c7bd - Maximilian Luz, 2019-09-23 : Merge pull request #5 from StollD/feature/sign-for-secureboot
☑ f799a0c3db07 - Dorian Stoll, 2019-09-22 : Add secureboot pre-signing to the kernel
✅(merge commit) 1d902b520816 - Maximilian Luz, 2019-09-20 : Merge pull request #3 from StollD/bugfix/touch-rotation
✅(merge commit) 5b57c79edb6f - Maximilian Luz, 2019-09-19 : Merge pull request #2 from qzed/v5.3-surface-devel-i915update
✅(legacy-i915) f8c1e1fdc0d8 - Chris Wilson, 2019-09-04 : drm/i915: Restore relaxed padding (OCL_OOB_SUPPRES_ENABLE) for skl+
✅(legacy-i915) 7824ac5da789 - Ville Syrjälä, 2019-08-28 : drm/i915: Limit MST to <= 8bpc once again
🚳(bugfix/touch-rotation) 86f95d24802f - Dorian Stoll, 2019-09-18 : Remove IPTS sensor mode APIs
🚳(bugfix/touch-rotation) 464d29dae4d3 - kitakar5525, 2019-08-28 : ipts: hid-multitouch: revert all the changes
✅(merge commit) ce721a4f1a70 - Maximilian Luz, 2019-09-18 : Merge pull request #1 from StollD/feature/i915-legacy-5.2.15
✅(legacy-i915) 54590f611539 - Lionel Landwerlin, 2019-06-28 : drm/i915/icl: whitelist PS_(DEPTH|INVOCATION)_COUNT
✅(legacy-i915) 439a55e961b9 - John Harrison, 2019-06-17 : drm/i915: Add whitelist workarounds for ICL
✅(legacy-i915) 567c377c7238 - Lionel Landwerlin, 2019-06-28 : drm/i915: whitelist PS_(DEPTH|INVOCATION)_COUNT
✅(legacy-i915) b9c9de448c7b - John Harrison, 2019-06-17 : drm/i915: Support whitelist workarounds on all engines
✅(legacy-i915) 9af88b4a7124 - John Harrison, 2019-06-17 : drm/i915: Support flags in whitlist WAs
✅(legacy-i915) 8fd23fbbf4cf - Ville Syrjälä, 2019-07-17 : drm/i915: Make sure cdclk is high enough for DP audio on VLV/CHV
✅(legacy-i915) d0a080d1450d - Kenneth Graunke, 2019-06-25 : drm/i915: Disable SAMPLER_STATE prefetching on all Gen11 steppings.
❓(not sure if needed for 4.19) 44c79ab7069e - Maximilian Luz, 2019-09-18 : surface_acpi: Test keeping EC alive for suspend
❌(old-patches-cleanup) 434376f84af6 - Maximilian Luz, 2019-09-18 : Revert downstream_hpd_needs_d0 changes in i915_legacy
❌(old-patches-cleanup) 09372baa5f2e - Maximilian Luz, 2019-09-18 : Revert "wireless: Add mwlwifi driver"
❌(old-patches-cleanup) 71867ba1077b - Maximilian Luz, 2019-09-18 : Revert "power/suspend: Add delay for device quirks"
❌(old-patches-cleanup) a13b184ccc47 - Maximilian Luz, 2019-09-18 : Revert "staging: Add WIP camera drivers for Surface devices"
❌(old-patches-cleanup) 810a01920dd9 - Maximilian Luz, 2019-09-18 : Revert "USB: Modify lpm check for sdcard-reader"
☑ 871f0898981a - Maximilian Luz, 2019-09-18 : Add support for Intel IPTS touch devices
✅(legacy-i915) 000367407533 - Dorian Stoll, 2019-09-16 : integrate legacy i915
✅(legacy-i915) 54ae106f6a3c - Dorian Stoll, 2019-09-16 : add legacy i915
☑ 711bc72ad506 - Maximilian Luz, 2019-09-18 : USB: Modify lpm check for sdcard-reader
☑ 367d6a9191b6 - qzed, 2019-09-18 : wireless/mwifiex: Add quirks for Surface devices
☑ 8ec42424d7fa - qzed, 2019-09-18 : staging: Add WIP camera drivers for Surface devices
☑ 7dca9b4732a5 - qzed, 2019-09-18 : power/suspend: Add delay for device quirks
☑ 118195afacbb - qzed, 2019-09-17 : USB: serial: Register Surface Go LTE device
☑ 96f527313bfc - qzed, 2019-09-17 : wireless: Add mwlwifi driver
☑ b4c1b84e1bae - qzed, 2019-09-17 : platform/x86: Surface 3 battery platform operation region support
☑ 8902494c240c - qzed, 2019-09-17 : HID: quirks for Microsoft Surface devices
☑ 2b6071ebe1d9 - Maximilian Luz, 2019-07-02 : platform/x86: Add support for Surface Book 2 dGPU
☑ 3fea36750112 - Maximilian Luz, 2019-07-27 : Input: soc_button_array - Add support for newer surface devices
☑ 5f679de09c4c - Maximilian Luz, 2019-07-27 : platform/x86: surfacepro3_button: Fix device check
☑ 99535b3ec62e - qzed, 2019-08-26 : platform: Add gen5 MS Surface platform support
✅(outdated-patch) a39043f4ebb7 - qzed, 2019-08-26 : serdev: Find ACPI clients by ResourceSource tag
☑ 07db8ff61bb0 - qzed, 2019-08-26 : ACPI: Fix buffer/integer type mismatch
4d856f72c10e - Linus Torvalds, 2019-09-15 : Linux 5.3

</p>
</details>

<details><summary>5.4</summary>
<p>

☑ cd9559fc7045 - kitakar5525, 2020-01-11 : Surface3-OEMB: surface3-wmi: add quirk for Surface 3 with broken DMI table
☑ cd400a8e78ae - Chih-Wei Huang, 2018-09-18 : Surface3-OEMB: ASoC: add quirk for Surface 3 with broken DMI table
☑ e6ca5caaad05 - Maximilian Luz, 2019-12-30 : surface_acpi: Remove indirect dependencies
☑ 66c840113c7f - kitakar5525, 2019-12-06 : surface3-spi: workaround: disable DMA mode to avoid crash by default
☑ 94e747ed71dd - Maximilian Luz, 2019-12-27 :  surface_acpi: Integrate dGPU hot-plug system
☑ 60628839372b - Maximilian Luz, 2019-12-27 : Revert "platform/x86: Add support for Surface Book 2 dGPU"
🉐(wifi-suspend-fix) c8da40c0538a - sebanc, 2019-11-04 : wireless/mwifiex: Fix S0ix / suspend
🉐(wifi-suspend-fix) 264427bb5816 - Maximilian Luz, 2019-12-18 : Revert "wireless/mwifiex: Add quirks for Surface devices"
❓(not sure if needed for 4.19) f05900c3d96c - Maximilian Luz, 2019-12-11 : surface_acpi: Simplify SSH irq setup
☑ 569f1f0a0549 - qzed, 2019-09-18 : wireless/mwifiex: Add quirks for Surface devices
☑ d8ce4703a137 - qzed, 2019-09-17 : USB: serial: Register Surface Go LTE device
☑ 90b9633c3000 - qzed, 2019-09-17 : platform/x86: Surface 3 battery platform operation region support
☑ 8ff12dfb6b44 - Maximilian Luz, 2019-07-02 : platform/x86: Add support for Surface Book 2 dGPU
☑ 6a65883807e7 - Maximilian Luz, 2019-12-06 : platform/x86: Add gen5 MS Surface platform support
⚪(in 4.19 and 5.4) 4bea4a71bf6a - Maximilian Luz, 2019-09-24 : serdev: Add ACPI devices by ResourceSource field
☑ 422a4903e47b - qzed, 2019-08-26 : ACPI: Fix buffer/integer type mismatch
☑ 09f1c1c8149e - Blaž Hrastnik, 2019-11-06 : HID: Improve Windows Precision Touchpad detection.
☑ 8d101066d485 - Tuowen Zhao, 2019-10-16 : docs: driver-model: add devm_ioremap_uc
☑ f3e1eb2f2c53 - Tuowen Zhao, 2019-10-16 : mfd: intel-lpss: use devm_ioremap_uc for MMIO
☑ 04f6483d6d55 - Tuowen Zhao, 2019-10-16 : lib: devres: add a helper function for ioremap_uc
☑ fa03b4ccadb5 - Tuowen Zhao, 2019-10-16 : sparc64: implement ioremap_uc
☑ 073fd9a84f68 - Dorian Stoll, 2019-09-22 : Add secureboot pre-signing to the kernel
219d54332a09 - Linus Torvalds, 2019-11-24 : Linux 5.4

</p>
</details>

## backporting

@qzed
I left the following commits because I think surface_sam modules are developed for both 4.19 and 5.4 and I assume the modules for 4.19 is already up-to-date. Is this OK?
❓(not sure if needed for 4.19) e05aa9d2c9cd - Maximilian Luz, 2019-09-26 : platform/x86: Update surface-acpi
❓(not sure if needed for 4.19) 8667db5d1899 - Maximilian Luz, 2019-09-26 : serdev: Update ACPI lookup fix
❓(not sure if needed for 4.19) 44c79ab7069e - Maximilian Luz, 2019-09-18 : surface_acpi: Test keeping EC alive for suspend
❓(not sure if needed for 4.19) f05900c3d96c - Maximilian Luz, 2019-12-11 : surface_acpi: Simplify SSH irq setup

The whole kernel built without errors and running well.
I'll split backports into multiple branches and make multiple PRs tomorrow.

**Comment by qzed** [comment]
> I left the following commits because I think surface_sam modules are developed for both 4.19 and 5.4 and I assume the modules for 4.19 is already up-to-date. Is this OK?

That's correct. Looks good to me, thanks!

**Comment by kitakar5525** [comment]
OK, thank you for the confirmation!
