### ISSUE TITLE
Proper device names in IPTS driver

### ISSUE THREAD

**Issue by qzed** [linux-surface/kernel#4]
My little concern is that we cannot distinguish touch devices by name anymore:
```bash
# before
$ libinput list-devices | grep ipts
Device:           ipts 1B96:005E UNKNOWN
Device:           ipts 1B96:005E
Device:           ipts 1B96:005E Touchscreen
Device:           ipts 1B96:005E Mouse

# after
$ libinput list-devices | grep ipts
Device:           ipts 1B96:005E
Device:           ipts 1B96:005E
```

No impact on functionality, though.
I hope we can change the name by IPTS driver side rather than patching to hid-multitouch.c at some point, like `ipts 1B96:005E Pen` and `ipts 1B96:005E Touchscreen` (for human).

(The `ipts 1B96:005E UNKNOWN` device was a single-touch device.)
(I don't know what was the purpose of the `ipts 1B96:005E Mouse`. It seems to be not used by any input for me.)

_Originally posted by @kitakar5525 in https://github.com/qzed/linux-surface-kernel/pull/3#issuecomment-533773770_

**Comment by qzed** [comment]
@kitakar5525 Right, we should probably use better device names for this. For classical USB devices, the name is (as far as I know) supplied by the device attached to the bus. It would also be nice if we could get some naming that is properly understandable for non-developers (e.g. `Microsoft Surface IPTS Touchscreen` and `Microsoft Surface IPTS Stylus`), where the prefix would ideally be supplied by attached the device itself somehow (or maybe the firmware files?).

**Comment by qzed** [comment]
Names are set here:

https://github.com/qzed/linux-surface-kernel/blob/1d902b5208160d98d1e35f690d3c47d97c2193fc/drivers/misc/ipts/ipts-hid.c#L284-L285

**Comment by StollD** [comment]
> Edit: I am currently not sure how this creates multiple input devices and how we can give them different names.

IPTS creates one single `hid_device` and uses it to forward all (hardware-generated) HID events to the kernels hid subsystem. There, they are split into multiple `hid_input`s (using the HID descriptor I believe), which are then processed by `hid-multitouch` etc.

The IPTS driver is not much more than a relay for those messages. If we wanted to split them into two seperate devices that can be controlled from IPTS we would have to reprocess the HID messages coming from the hardware / firmware.

**Comment by qzed** [comment]
@StollD Thanks, makes sense. So we don't have direct control over the suffix, at least without changing hid system internals, which then would probably involve some convincing of the upstream maintainers if we ever get to upstream this.

**Comment by qzed** [comment]
Closing this as that's an issue with the old IPTS driver.
