### ISSUE TITLE
Backport changes on 5.6 to 5.4

### ISSUE THREAD

**Issue by qzed** [linux-surface/kernel#46]
Backport newer changes to 5.4, especially the new IPTS driver. This is motivated by a discussion on Gitter. Basically, on the Pro 7 there seem to be some upstream issues with the iGPU, causing freezes on v5.5+. It would thus help some people to have patches including the latest wifi fixes and IPTS driver on v5.4, even if we don't build binary releases.

We should probably remove the old 5.4 branch and start fresh based on the 5.6 patches.

**Comment by kitakar5525** [comment]
All of the commits from me that is relevant to v5.4 are applied to v5.4

I guess starting freshly may not be needed but I'll leave it to you.

Regarding the other commits, as far as I know:

#### backported by upstream

ioremap_uc
- "sparc64: implement ioremap_uc" (ours: fa03b4ccadb5d7) has been backported on v5.4.3 as c3277e67a93bb2
- "lib: devres: add a helper function for ioremap_uc" (ours: 04f6483d6d55f6) has been backported on v5.4.40 as 78b19f56b95240

(btw, the commit "lib: devres: add a helper function for ioremap_uc" is also backported on v4.19.122 as ccc4433062ce80)

hid
- "HID: Improve Windows Precision Touchpad detection." (ours: 09f1c1c8149e9b) has been backported on v5.4.8 as 65889bba7be124

#### missing

surface-sam
- commit 08e8fc452eb775 ("surface_acpi: Add HPS dependency on GPIO_SYSFS in KConfig") is missing
- commit fa33900921a065 ("surface_acpi: Update based on module") is missing

ipts: all of the commits are missing
- there is small conflict on commit 72eb2084dcd53d ("uapi: Add MEI bus ID") but easily resolved by auto-merging or something
- ipts driver actually works on v5.4

**Comment by kitakar5525** [comment]
So, functionally, all of the `ioremap_uc`patches are included on v5.4 (and also on v4.19 [1]) recently.

v5.4-surface-devel and v4.19-surface-devel has the additional docs patch: "docs: driver-model: add devm_ioremap_uc" but not on upstream v5.4 and v4.19 (at least yet?)

[1]
btw, the following commits are also backported into v4.19:
- "mfd: intel-lpss: Use devm_ioremap_uc for MMIO" (ours: d63f1658577c26) is also backported  on v4.19.122 as e06a89985c585f
- "lib: devres: add a helper function for ioremap_uc" (ours: 32bfaf2668b1a9) is also backported on v4.19.122 as ccc4433062ce80

**Comment by qzed** [comment]
Thanks! I'll probably have a go at this later. Seems like its probably easier to update the current 5.4. I  think the docs commit will not be backported as its just for documentation. It's not important for functionality.

**Comment by qzed** [comment]
`v5.4-surface-devel` should be updated. Have yet to test it.

**Comment by qzed** [comment]
There was a merge conflict when rebasing onto v5.4.41, so I've force-pushed the rebased to 5.4-surface-devel so that we don't have to deal with that again in the future.

**Comment by kitakar5525** [comment]
I built 5.4.41 Arch kernel myself. It's working properly regarding linux-surface patches.

Also, current `v5.4-surface-devel` branch looks good to me, except the following difference to `v5.4-surface`:
```diff
$ git diff v5.4-surface-devel v5.4-surface
diff --git a/Documentation/driver-api/driver-model/devres.rst b/Documentation/driver-api/driver-model/devres.rst
index 92628fdc2f11..a100bef54952 100644
--- a/Documentation/driver-api/driver-model/devres.rst
+++ b/Documentation/driver-api/driver-model/devres.rst
@@ -314,7 +314,6 @@ IOMAP
   devm_ioport_unmap()
   devm_ioremap()
   devm_ioremap_nocache()
-  devm_ioremap_uc()
   devm_ioremap_wc()
   devm_ioremap_resource() : checks resource, requests memory region, ioremaps
   devm_iounmap()
diff --git a/drivers/input/touchscreen/ipts/init.c b/drivers/input/touchscreen/ipts/init.c
index fb70d55542af..6c2dcd88ce07 100644
--- a/drivers/input/touchscreen/ipts/init.c
+++ b/drivers/input/touchscreen/ipts/init.c
@@ -1,6 +1,5 @@
 // SPDX-License-Identifier: GPL-2.0-or-later
 
-#include <linux/dma-mapping.h>
 #include <linux/mei_cl_bus.h>
 #include <linux/module.h>
 #include <linux/mod_devicetable.h>
@@ -21,17 +20,6 @@ static int ipts_init_probe(struct mei_cl_device *cldev,
 
        dev_info(&cldev->dev, "Probing IPTS\n");
 
-       // Setup the DMA bit mask
-       if (!dma_coerce_mask_and_coherent(&cldev->dev, DMA_BIT_MASK(64))) {
-               dev_info(&cldev->dev, "IPTS using DMA_BIT_MASK(64)\n");
-       } else if (!dma_coerce_mask_and_coherent(&cldev->dev,
-                       DMA_BIT_MASK(32))) {
-               dev_info(&cldev->dev, "IPTS using DMA_BIT_MASK(32)");
-       } else {
-               dev_err(&cldev->dev, "No suitable DMA for IPTS available\n");
-               return -EFAULT;
-       }
-
        ret = mei_cldev_enable(cldev);
        if (ret) {
                dev_err(&cldev->dev, "Cannot enable IPTS\n");
```

- I guess docs patches for  `ioremap_uc` is intentionally dropped?
- wrt the DMA thing, those lines don't exist on `v5.4-surface` but exist on generated linux-surface patches. So, I guess some accident happened?
  btw, on SB1, ipts works with those DMA lines (built kernel with patches from linux-surface repo).

**Comment by qzed** [comment]
The `ioremap_uc` doc is intentionally dropped, yes. Without the doc patch we don't need to have a separate patch for `ioremap_uc`.

I forgot to push the DMA change, so it didn't end up in `v5.4-surface`. Thanks for noticing! Should be fixed now.
