### ISSUE TITLE
WiFi broke on kernel 5.8.3

### ISSUE THREAD

**Issue by sleepyeldrazi** [linux-surface/kernel#54]
Device: Surface Book 2
Distro: Manjaro
Previous Kernel: 5.8.1
Kernel After Update: 5.8.3
Date of Update: 24. Aug 2020
Kernel downloaded through yay from the repo: https://pkg.surfacelinux.com/arch/

I should mention that i couldn't connect to neither the 2.4GHz nor 5Ghz network from my router. I was however able to connect to a mobile hotspot (OnePlus 6T). After downgrading to 5.8.1 the issue was instantly resolved. I will attempt to build from commit https://github.com/linux-surface/kernel/commit/233bcf2785b47254b2d1f5c5381d47e8891b2c63 and see if works there.

**Comment by qzed** [comment]
I can't reproduce this on my SB2 with my home WiFi. There haven't been any changes between 5.8.1 to 5.8.3 to the WiFi drivers from our side, so if any change caused this, it should be an upstream one. If you want to track this down, you should merge upstream v5.8.3 on top of v5.8-surface-devel (which is based off of v5.8) and bisect from there.

**Comment by qzed** [comment]
As far as I can tell, this seems to be the only commit to mwifiex that could cause something like this: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.8.y&id=bc2599182f8ec577ca81a6de40349e94fb9734df

**Comment by sleepyeldrazi** [comment]
Small update, the kernel from the commit i mentioned (https://github.com/linux-surface/kernel/commit/233bcf2785b47254b2d1f5c5381d47e8891b2c63) doesn't have this problem. I am currently trying to setup anbox, after which i might investigate why the WiFi wasn't working as intended on 5.8.3 . My kernel knowledge is pretty bad but I will try to do my best to find the issue.

**Comment by elChupaCambra** [comment]
Wanted to chime in and say I have been having this issue since last night on my Surface Pro 6 too. WiFi works out of the box after installation of a distro, but fails to authenticate with my home WiFi password-protected network after installing the Linux-Surface kernel. Simply keeps asking to introduce the password. Occurs on Ubuntu 20.04 (and derivatives Pop_OS and KDE Neon) as well as Manjaro.

Connects to my phone hotspot fine but not to my home WiFi network. WiFi works perfectly on Windows, but no surprises there.

**Comment by sleepyeldrazi** [comment]
> Wanted to chime in and say I have been having this issue since last night on my Surface Pro 6 too. WiFi works out of the box after installation of a distro, but fails to authenticate with my home WiFi password-protected network after installing the Linux-Surface kernel. Simply keeps asking to introduce the password. Occurs on Ubuntu 20.04 (and derivatives Pop_OS and KDE Neon) as well as Manjaro.
> 
> Connects to my phone hotspot fine but not to my home WiFi network. WiFi works perfectly on Windows, but no surprises there.

Exactly the same behavior as me then, I forgot to mention the repeated asking for the password.

**Comment by qzed** [comment]
@sleepyeldrazi I kind of expected that that commit works, as it's based on v5.8 and not v5.8.3. Can you try building a v5.8.3 kernel (e.g. from the `v5.8-surface`) and add some debug output to the commit I linked above? Specifically replace it with something like (adding in the `pr_err` calls):

```diff
diff --git a/drivers/net/wireless/marvell/mwifiex/sta_cmdresp.c b/drivers/net/wireless/marvell/mwifiex/sta_cmdresp.c
index f21660149f584..962d8bfe6f101 100644
--- a/drivers/net/wireless/marvell/mwifiex/sta_cmdresp.c
+++ b/drivers/net/wireless/marvell/mwifiex/sta_cmdresp.c
@@ -580,6 +580,11 @@ static int mwifiex_ret_802_11_key_material_v1(struct mwifiex_private *priv,
 {
 	struct host_cmd_ds_802_11_key_material *key =
 						&resp->params.key_material;
+	int len;
+
+	len = le16_to_cpu(key->key_param_set.key_len);
+	if (len > sizeof(key->key_param_set.key)) {
+		pr_err("mwifiex-DEBUG: len > sizeof(key->key_param_set.key in %s\n", __func__);
+		return -EINVAL;
+	}
 
 	if (le16_to_cpu(key->action) == HostCmd_ACT_GEN_SET) {
 		if ((le16_to_cpu(key->key_param_set.key_info) & KEY_MCAST)) {
@@ -593,9 +598,8 @@ static int mwifiex_ret_802_11_key_material_v1(struct mwifiex_private *priv,
 
 	memset(priv->aes_key.key_param_set.key, 0,
 	       sizeof(key->key_param_set.key));
-	priv->aes_key.key_param_set.key_len = key->key_param_set.key_len;
-	memcpy(priv->aes_key.key_param_set.key, key->key_param_set.key,
-	       le16_to_cpu(priv->aes_key.key_param_set.key_len));
+	priv->aes_key.key_param_set.key_len = cpu_to_le16(len);
+	memcpy(priv->aes_key.key_param_set.key, key->key_param_set.key, len);
 
 	return 0;
 }
@@ -610,9 +614,14 @@ static int mwifiex_ret_802_11_key_material_v2(struct mwifiex_private *priv,
 					      struct host_cmd_ds_command *resp)
 {
 	struct host_cmd_ds_802_11_key_material_v2 *key_v2;
-	__le16 len;
+	int len;
 
 	key_v2 = &resp->params.key_material_v2;
+
+	len = le16_to_cpu(key_v2->key_param_set.key_params.aes.key_len);
+	if (len > WLAN_KEY_LEN_CCMP)
+		pr_err("mwifiex-DEBUG: len > sizeof(key->key_param_set.key in %s\n", __func__);
+		return -EINVAL;
+	}
+
 	if (le16_to_cpu(key_v2->action) == HostCmd_ACT_GEN_SET) {
 		if ((le16_to_cpu(key_v2->key_param_set.key_info) & KEY_MCAST)) {
 			mwifiex_dbg(priv->adapter, INFO, "info: key: GTK is set\n");
@@ -628,10 +637,9 @@ static int mwifiex_ret_802_11_key_material_v2(struct mwifiex_private *priv,
 	memset(priv->aes_key_v2.key_param_set.key_params.aes.key, 0,
 	       WLAN_KEY_LEN_CCMP);
 	priv->aes_key_v2.key_param_set.key_params.aes.key_len =
-				key_v2->key_param_set.key_params.aes.key_len;
-	len = priv->aes_key_v2.key_param_set.key_params.aes.key_len;
+				cpu_to_le16(len);
 	memcpy(priv->aes_key_v2.key_param_set.key_params.aes.key,
-	       key_v2->key_param_set.key_params.aes.key, le16_to_cpu(len));
+	       key_v2->key_param_set.key_params.aes.key, len);
 
 	return 0;
 }
```

And then check the dmesg log.

**Comment by qzed** [comment]
The speed/bluetooth thing is a known issue and tracked somewhere on the linux-surface repo.

**Comment by elChupaCambra** [comment]
> 
> 
> I can't reproduce this on my SB2 with my home WiFi. There haven't been any changes between 5.8.1 to 5.8.3 to the WiFi drivers from our side, so if any change caused this, it should be an upstream one. If you want to track this down, you should merge upstream v5.8.3 on top of v5.8-surface-devel (which is based off of v5.8) and bisect from there.

Right, so here's what I did (Surface Pro 6):
1. Resize Windows 10 partition in Windows' Disk Management
2. Install Pop_OS 20.04 (Wi-Fi working)
3. Follow the linux-surface installation guide [here](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup) (Wi-Fi still working)
4. Reboot
5. Touchscreen etc. working under Linux-Surface kernel, **but can't connect to Wi-Fi network I was previously connecting to as per detailed in my prior comment**.

Please let me know if there's some way I can be of use; I'd like to also provide the dmesg log you asked @sleepyeldrazi for if it'd be of any use to you, but honestly I'm not super Linux-savvy and am lost as to how to help.

**Comment by qzed** [comment]
@elChupaCambra I assume that this can only be reproduced on certain network configurations. If my guess with the commit above is correct, it should depend on the key length (nb: key is not password here).

**Comment by sleepyeldrazi** [comment]
[dmesg.txt](https://github.com/linux-surface/kernel/files/5119840/dmesg.txt)
[dmesg_grep_mwifiex.txt](https://github.com/linux-surface/kernel/files/5119841/dmesg_grep_mwifiex.txt)
One is the complete dmesg, the other is with grep mwifiex. Sorry for the wait.

**Comment by qzed** [comment]
Alright, looks like my assumption was correct. The log reports a key size of 256 bit (32 bytes), but the storage is only 128 bit (16 bytes), and with the newly introduced check, it fails there. Given that it more or less worked before adding that check, I'd say we try upgrade that to 32 bytes. [Here](https://github.com/linux-surface/kernel/files/5120822/0001-mwifiex-Increase-AES-key-storage-size-to-256-bits.patch.txt)'s a patch that does that (don't be confused by the `.txt` ending, GitHub doesn't allow uploading patches in comments). Can you try applying that to the `v5.3-surface` branch and test again?

**Comment by sleepyeldrazi** [comment]
Doesn't seem to work, I'll re-add the pr_err and see if it gets the same errors.

**Comment by sleepyeldrazi** [comment]
[diff.txt](https://github.com/linux-surface/kernel/files/5122678/diff.txt)
Wifi works as expected now. Thanks for the support.

**Comment by elChupaCambra** [comment]
Hi @qzed and @leepyeldrazi, thanks for the hard work. How can a newbie like myself apply this patch? 

I have found the folder:
"/usr/lib/modules/5.8.3-arch1-1-surface/kernel/drivers/net/wireless/marvell/mwifiex/" which seems similar to the one you posted in your .txt files, except I can't find the "fw.h" or "sta_cmdresp.c" files on my Manjaro install. Is this because you guys are talking about files changed before building the linux-surface kernel? If so, could you point me to how I can apply this patch (or a resource that could show me how to do so?) 

Thank you for your time!

**Comment by sleepyeldrazi** [comment]
It'd be best if someone who understands the kernel better to write all this but if you're feeling experimental, here are my steps:

1. git clone the repo
2. checkout to the correct branch
3. patch the local repo
4. build the kernel and the modules (-j8 means "use all 8 threads", adjust this depending on your cpu and lower it if you don't want it to run hot / be unusable while building )
5. copy the generated image to /boot
6. make a new preset and edit it to match the new image (change vmlinuz-linux-surface to vmlinuz-linux-surfacefix and same for the initramfs)
7. build the initramfs with mkinitcpio
8. update grub to detect the new kernel
9. boot the correct kernel (surfacefix in this case) 

 ```bash
git clone https://github.com/linux-surface/kernel.git
cd kernel
git checkout -b v5.8-surface
wget -O diff.patch https://github.com/linux-surface/kernel/files/5122678/diff.txt
patch -p1 < diff.patch
make -j8
sudo make modules_install
sudo cp arch/x86/boot/bzImage /boot/vmlinuz-linux-surfacefix
cd /etc/mkinitcpio.d/
sudo cp linux-surface.preset linux-surfacefix.preset
sudo nano linux-surfacefix.preset
sudo mkinitcpio -p linux-surfacefix
sudo update-grub
```

I do highly recommend for you to wait a new commit with the patch though. Attempt this only if you have some spare time (since building the kernel might take over an hour) and aren't afraid to reinstall linux. I'm here if you need any assistance with this.

**Comment by qzed** [comment]
@sleepyeldrazi Do you have an email address that I can CC when sending the patch upstream?

**Comment by sleepyeldrazi** [comment]
You can use konik98@gmail.com

**Comment by qzed** [comment]
Thanks! I'll add you as tested-by, if that's okay with you.

**Comment by sleepyeldrazi** [comment]
> Alright, looks like my assumption was correct. The log reports a key size of 256 bit (32 bytes), but the storage is only 128 bit (16 bytes), and with the newly introduced check, it fails there. Given that it more or less worked before adding that check, I'd say we try upgrade that to 32 bytes. [Here](https://github.com/linux-surface/kernel/files/5120822/0001-mwifiex-Increase-AES-key-storage-size-to-256-bits.patch.txt)'s a patch that does that (don't be confused by the `.txt` ending, GitHub doesn't allow uploading patches in comments). Can you try applying that to the `v5.3-surface` branch and test again?

Oh I just noticed that you wanted me to try it on the 5.3 kernel, i got it working on the 5.8.3 (v5.8-surface), want me to try the v5.3-surface kernel now?

**Comment by qzed** [comment]
Sorry that was a typo. 5.8 is correct, so no need to try on 5.3.

**Comment by qzed** [comment]
Just sent out the patch.

**Comment by elChupaCambra** [comment]
> It'd be best if someone who understands the kernel better to write all this but if you're feeling experimental, here are my steps:
> 
>     1. git clone the repo
> 
>     2. checkout to the correct branch
> 
>     3. patch the local repo
> 
>     4. build the kernel and the modules (-j8 means "use all 8 threads", adjust this depending on your cpu and lower it if you don't want it to run hot / be unusable while building )
> 
>     5. copy the generated image to /boot
> 
>     6. make a new preset and edit it to match the new image (change vmlinuz-linux-surface to vmlinuz-linux-surfacefix and same for the initramfs)
> 
>     7. build the initramfs with mkinitcpio
> 
>     8. update grub to detect the new kernel
> 
>     9. boot the correct kernel (surfacefix in this case)
> 
> 
> ```shell
> git clone https://github.com/linux-surface/kernel.git
> cd kernel
> git checkout -b v5.8-surface
> wget -O diff.patch https://github.com/linux-surface/kernel/files/5122678/diff.txt
> patch -p1 < diff.patch
> make -j8
> sudo make modules_install
> sudo cp arch/x86/boot/bzImage /boot/vmlinuz-linux-surfacefix
> cd /etc/mkinitcpio.d/
> sudo cp linux-surface.preset linux-surfacefix.preset
> sudo nano linux-surfacefix.preset
> sudo mkinitcpio -p linux-surfacefix
> sudo update-grub
> ```
> 
> I do highly recommend for you to wait a new commit with the patch though. Attempt this only if you have some spare time (since building the kernel might take over an hour) and aren't afraid to reinstall linux. I'm here if you need any assistance with this.

Thanks for your reply and the instructions, @sleepyeldrazi. I'll take your suggestion and wait for for the new patch; though depending on how long that takes, I eventually try this anyway. :)

**Comment by qzed** [comment]
@elChupaCambra If it doesn't get included in v5.8.4 upstream, I'll likely add it to our patches until it's upstream.

**Comment by qzed** [comment]
New releases with the fix are currently building, the patches have been updated to contain the fix.

**Comment by sleepyeldrazi** [comment]
Thanks for all the help

**Comment by qzed** [comment]
New releases should be live in a couple of minutes.

**Comment by luca-viggiani** [comment]
Hi I have the same issue with wifi (MS SP 4) with current 5.8.10 surface-linux as well as 5.8.11 arch linux std kernel. The last good for me is standard arch linux kernel 5.8.5 provided in the last installation usb media.

**Comment by qzed** [comment]
If it works with 5.8.5, this seems to be a different issue: The original issue was caused by a change in 5.8.3 and fixes are only now being backported to stable releases (seems like 5.8.13 will be the first include it). Arch 5.8.5 does not include the fix for the issue described in this thread, so if it were this issue, it shouldn't work on that.
